### ISSUE TITLE
New 3ds 11.0 usa failed to complete safehax

### ISSUE THREAD

**Issue by TheProgrammerEX** [TiniVi/safehax#3] opened 2017-01-03 02:04 UTC
while this was running safehax I came along the picture below
![win_20170102_21_03_47_pro](https://cloud.githubusercontent.com/assets/21089275/21598687/fccde6d4-d12e-11e6-9233-2ea06a8e87fb.jpg)

I'm not sure if thats normal and i just have to try again or not but that was my second attempt.

**Comment by TiniVi** [comment] 2017-01-03 02:38
The screen glitch is normal, the hang is not. I'm looking into the issue.

**Comment by TheProgrammerEX** [comment] 2017-01-03 03:54
Oh, if it helps, i'm using steelhax with 2.7 *hax

**Comment by cermakondrej** [comment] 2017-01-03 04:01
After successful waithax -> return to HBL and starting safehax, i get blackscreen , confirmed with other 4 people, who have same issues

**Comment by mariogamer2** [comment] 2017-01-03 04:39
Try using soundhax.

**Comment by Shawntastic** [comment] 2017-01-03 05:05
When I start safe hax after succesfully installing waithax I just get "PM init failed" help with this please

**Comment by mariogamer2** [comment] 2017-01-03 05:06
Try using the new revision of waithax.

**Comment by Shawntastic** [comment] 2017-01-03 05:10
Will try what and see how it goes, thanks

**Comment by TiniVi** [comment] 2017-01-03 08:45
Technically, this is a duplicate of #5, so I'll close this issue.

**Closed as completed by TiniVi** 2017-01-03 08:45 UTC
